In [1]:
#Reduction Src : deeplizard youtube

In [2]:
import torch
import numpy as np

In [3]:
t = torch.randn(3,3, dtype = torch.float32)

In [4]:
t

tensor([[ 0.0447,  0.2794, -0.6715],
        [-0.9684, -0.0264,  0.1730],
        [-0.3195, -1.1811, -0.7290]])

In [5]:
t.sum() #reduction operation

tensor(-3.3986)

In [6]:
t.numel()

9

In [7]:
t.sum().numel()

1

In [8]:
t.mean()

tensor(-0.3776)

In [9]:
t.std()

tensor(0.5297)

In [11]:
t2 = torch.randn(1000, 1000)

In [12]:
t2.mean()

tensor(0.0005)

In [13]:
t2.std()

tensor(0.9998)

In [15]:
t3 = torch.randn(3,4)
print(t3)
t3.sum(dim=0) # column-wise

tensor([[-1.0807, -0.5621,  2.0727,  0.4616],
        [-0.7379,  0.2022,  0.9651, -0.5227],
        [ 0.6383,  1.3447, -1.0479, -0.1896]])


tensor([-1.1803,  0.9848,  1.9900, -0.2508])

In [16]:
t3.sum(dim=1)

tensor([ 0.8916, -0.0934,  0.7455])

In [17]:
-1.08-0.73+0.63

-1.1800000000000002

In [21]:
t3.max(dim=0)

torch.return_types.max(
values=tensor([0.6383, 1.3447, 2.0727, 0.4616]),
indices=tensor([2, 2, 0, 0]))

In [22]:
t3.max(dim=0).values

tensor([0.6383, 1.3447, 2.0727, 0.4616])

In [23]:
t3.max(dim=0).indices

tensor([2, 2, 0, 0])

In [25]:
t.mean().shape # 0d tensor

torch.Size([])