In [1]:
import torch
import numpy as np

In [2]:
data = np.array([1,2,3])

In [3]:
t1 = torch.Tensor(data) #constructor
t2 = torch.tensor(data) #Factory function
t3 = torch.as_tensor(data) #Factory fn
t4 = torch.from_numpy(data)

In [4]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [5]:
torch.get_default_dtype()

torch.float32

In [6]:
#type in factory fns are inferred baed on incoming data

In [7]:
torch.tensor(data, dtype = torch.float64) #explicitly set type

tensor([1., 2., 3.], dtype=torch.float64)

In [8]:
data[0]=0
data[1]=0
data[2]=0

In [9]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 0, 0])
tensor([0, 0, 0])


In [11]:
#best option -> torch.tensor()
#other best / mem option -> torch.as_tensor()