In [1]:
from IPython.core.debugger import set_trace

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [4]:
A = torch.randn((5,3))

h(help)<- Help  
n(ext) <- Continue execution until the next line in the current function is reached or it returns  
s(tep) <- Execute the current line, stop at first possible occasion, either in function that is called or in current function  
r(eturn) <- continue executing until the function returns  
a(args) <- print argument list of current function  

In [13]:
def function():
    A.shape
    set_trace()
    A.add_(1)
    set_trace()
    A.mul_(5)
    return A
function()

> <ipython-input-13-ee4ad5c2a808>(4)function()
      2     A.shape
      3     set_trace()
----> 4     A.add_(1)
      5     set_trace()
      6     A.mul_(5)

ipdb> A
tensor([[10.9173, 32.9923, 14.2542],
        [-4.7493, 15.8435, 24.1947],
        [25.7704, -7.7290, 35.8976],
        [47.6310, 26.4693, 41.7798],
        [50.9628, 44.3755, 54.8367]])
ipdb> n
> <ipython-input-13-ee4ad5c2a808>(5)function()
      3     set_trace()
      4     A.add_(1)
----> 5     set_trace()
      6     A.mul_(5)
      7     return A

ipdb> A
tensor([[11.9173, 33.9923, 15.2542],
        [-3.7493, 16.8435, 25.1947],
        [26.7704, -6.7290, 36.8976],
        [48.6310, 27.4693, 42.7798],
        [51.9628, 45.3755, 55.8367]])
ipdb> n
> <ipython-input-13-ee4ad5c2a808>(6)function()
      4     A.add_(1)
      5     set_trace()
----> 6     A.mul_(5)
      7     return A
      8 function()

ipdb> A
tensor([[11.9173, 33.9923, 15.2542],
        [-3.7493, 16.8435, 25.1947],
        [26.7704, -6.7290, 36.8976],


BdbQuit: 

In [9]:
set_trace?

In [14]:
scalar = torch.tensor(3)

In [19]:
scalar.shape

torch.Size([])