In [2]:
import torch

In [19]:
t = torch.tensor([1,2,3] )
T = torch.Tensor([1,2,3])

In [22]:
print(t.dtype)
print(T.dtype)

torch.int64
torch.float32


In [4]:
t=t.cuda()

In [5]:
t

tensor([1, 2, 3], device='cuda:0')

In [12]:
device = torch.device('cuda:0')

In [13]:
device

device(type='cuda', index=0)

In [17]:
device_cpu = torch.device('cpu:0')

In [15]:
device_cpu

device(type='cpu', index=0)

In [9]:
t2.flatten()

tensor([-0.7781,  0.1501, -0.3234,  1.1087,  0.6057,  0.1117])

In [10]:
#Rank of a tensor
# rank of t = 1
# rank of t2 = 2

#Length of a tensor
# how many indices
# t has length 2
# Shape of a tensor
# Rank of a tensor is the length of its shape

In [11]:
t.dtype

torch.int64

In [24]:
t + 1

tensor([2, 3, 4])

In [26]:
t.mean()

RuntimeError: Can only calculate the mean of floating types. Got Long instead.