In [1]:
import torch

In [5]:
t = torch.randn(3,4, dtype = torch.float32)

In [6]:
t

tensor([[ 0.7583,  1.0875,  1.0903,  0.7434],
        [-0.2346,  1.9540,  0.4715, -0.3888],
        [ 0.0059, -0.3108, -0.8429,  1.6835]])

In [7]:
t.shape

torch.Size([3, 4])

In [8]:
len(t.shape) #

2

In [9]:
torch.tensor(t.shape).prod()

tensor(12)

In [10]:
t.numel() # number of elements

12

In [19]:
print(t.reshape(1,12))#rank 2 D array
print(t.reshape(1,12).shape)
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape) # rank 1 o 1D array

tensor([[ 0.7583,  1.0875,  1.0903,  0.7434, -0.2346,  1.9540,  0.4715, -0.3888,
          0.0059, -0.3108, -0.8429,  1.6835]])
torch.Size([1, 12])
tensor([ 0.7583,  1.0875,  1.0903,  0.7434, -0.2346,  1.9540,  0.4715, -0.3888,
         0.0059, -0.3108, -0.8429,  1.6835])
torch.Size([12])


In [22]:
t

tensor([[ 0.7583,  1.0875,  1.0903,  0.7434],
        [-0.2346,  1.9540,  0.4715, -0.3888],
        [ 0.0059, -0.3108, -0.8429,  1.6835]])

In [23]:
t.flatten().shape

torch.Size([12])